# 預測是否會土石流

# import packages

In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.externals.six import StringIO   
from sklearn.tree import export_graphviz
import pydotplus
import numpy as np


# Attributes and Features

*坡度         -> 0~30度
*土砂原料     -> 多:1，少:0
*累積雨量     -> 0~400毫米
*人為開發程度 -> 高:1，低:0
*地質年代     -> 年輕:1，老:0

# generate data

In [2]:
data=pd.DataFrame(np.random.randint(0,30,size=(1500,1)),columns = ['gradient'])
data['raw material']=np.random.choice(list({'0','1'}),len(data))
data['human']=np.random.choice(list({'0','1'}),len(data))
data['raw material']=np.random.choice(list({'0','1'}),len(data))
data['geology']=np.random.choice(list({'0','1'}),len(data))
data

gradient raw material human geology
0           27            1     1       0
1           19            0     1       0
2            2            0     0       1
3            5            1     0       0
4           23            0     1       1
5            6            1     0       0
6            1            1     0       1
7           27            1     0       0
8           20            1     1       1
9           20            1     0       1
10          15            0     0       1
11           3            0     1       1
12           0            0     1       0
13          18            0     0       0
14          10            0     1       0
15          13            0     0       1
16          29            1     0       0
17           1            0     1       1
18           3            1     1       0
19          24            1     1       0
20          25            1     0       0
21           6            0     1       1
22          29            1     0       0
23          14            1     0       1
24          23            0     1       1
25          27            1     0       0
26          27            0     1       0
27           1            0     1       1
28          13            0     0       1
29           0            1     1       0
...        ...          ...   ...     ...
1470        28            0     1       0
1471        29            0     0       0
1472        29            0     0       1
1473        29            0     1       0
1474         8            1     1       1
1475        18            0     0       0
1476        14            0     0       1
1477         5            1     1       1
1478         6            0     1       0
1479        28            1     0       1
1480         5            0     1       0
1481         8            0     1       1
1482         5            0     0       1
1483        22            0     1       1
1484        20            1     1       0
1485         2            0     1       1
1486        19            0     0       0
1487         0            0     0       1
1488        13            1     0       1
1489         3            0     0       1
1490        23            1     0       1
1491        19            1     0       0
1492        23            0     0       1
1493        16            0     1       0
1494        28            1     1       1
1495        14            0     1       0
1496        20            0     0       1
1497        10            1     0       1
1498         2            0     0       1
1499        20            0     0       0

[1500 rows x 4 columns]

In [ ]:
data['rain'] = np.random.normal(0, 400, len(data))
data

In [6]:
def pos(x):
    if x<0:
        return float(abs(x))
    return float(x)
data.rain=data.rain.apply(pos)

In [7]:
data.head()

gradient raw material human geology        rain
0        27            1     1       0  650.559199
1        19            0     1       0  116.002018
2         2            0     0       1  270.352014
3         5            1     0       0  528.061775
4        23            0     1       1  380.106347

evaluate the 'right' result

In [9]:
def mapping(x):
    if x.rain>=360:
        if x.gradient>=15 and x.gradient<=30:
            return 'may'
        else:
            if x['raw material']==1:
                return 'may'
            else:
                if x['geology']==1:
                    return 'may'
                else:
                    if x['human']==1:
                        return 'may'
                    else:
                        return 'maynot'
    else:
        if x.gradient<15:
            return 'maynot'
        else:
            if x['raw material']==1:
                return 'may'
            else: 
                return 'maynot'          

In [10]:
data['happen']=data.apply(mapping,axis=1)

In [11]:
data

gradient raw material human geology         rain  happen
0           27            1     1       0   650.559199     may
1           19            0     1       0   116.002018  maynot
2            2            0     0       1   270.352014  maynot
3            5            1     0       0   528.061775  maynot
4           23            0     1       1   380.106347     may
5            6            1     0       0   269.884942  maynot
6            1            1     0       1   598.719743  maynot
7           27            1     0       0   151.116415  maynot
8           20            1     1       1   278.180118  maynot
9           20            1     0       1   173.635888  maynot
10          15            0     0       1   160.894157  maynot
11           3            0     1       1   185.259225  maynot
12           0            0     1       0    88.689673  maynot
13          18            0     0       0   344.878035  maynot
14          10            0     1       0   209.870856  maynot
15          13            0     0       1   403.433008  maynot
16          29            1     0       0   207.522846  maynot
17           1            0     1       1    78.629495  maynot
18           3            1     1       0    33.335408  maynot
19          24            1     1       0   627.208081     may
20          25            1     0       0   105.456536  maynot
21           6            0     1       1   193.159114  maynot
22          29            1     0       0   123.901464  maynot
23          14            1     0       1   102.943538  maynot
24          23            0     1       1   841.880981     may
25          27            1     0       0   272.582961  maynot
26          27            0     1       0   583.681590     may
27           1            0     1       1   150.234867  maynot
28          13            0     0       1   279.346477  maynot
29           0            1     1       0   810.470696  maynot
...        ...          ...   ...     ...          ...     ...
1470        28            0     1       0   167.957660  maynot
1471        29            0     0       0   319.574178  maynot
1472        29            0     0       1    19.845956  maynot
1473        29            0     1       0   795.594755     may
1474         8            1     1       1   582.129321  maynot
1475        18            0     0       0   419.691776     may
1476        14            0     0       1   246.063109  maynot
1477         5            1     1       1    35.723639  maynot
1478         6            0     1       0    63.649025  maynot
1479        28            1     0       1   545.638947     may
1480         5            0     1       0   464.654276  maynot
1481         8            0     1       1   209.778985  maynot
1482         5            0     0       1   224.576238  maynot
1483        22            0     1       1   680.696615     may
1484        20            1     1       0   107.652019  maynot
1485         2            0     1       1   128.588695  maynot
1486        19            0     0       0   246.409520  maynot
1487         0            0     0       1   216.797079  maynot
1488        13            1     0       1   150.185757  maynot
1489         3            0     0       1   216.469836  maynot
1490        23            1     0       1  1001.970534     may
1491        19            1     0       0   552.693017     may
1492        23            0     0       1   237.013214  maynot
1493        16            0     1       0   647.174232     may
1494        28            1     1       1   225.564670  maynot
1495        14            0     1       0   303.131732  maynot
1496        20            0     0       1   297.690565  maynot
1497        10            1     0       1    61.259417  maynot
1498         2            0     0       1   131.624641  maynot
1499        20            0     0       0   233.229062  maynot

[1500 rows x 6 columns]

In [12]:
def happen(x):
    if x=='may':
        x=1
    elif x=='maynot':
        x=0
    return x
data.happen=data.happen.apply(happen)

In [13]:
data.head()

gradient raw material human geology        rain  happen
0        27            1     1       0  650.559199       1
1        19            0     1       0  116.002018       0
2         2            0     0       1  270.352014       0
3         5            1     0       0  528.061775       0
4        23            0     1       1  380.106347       1

# Seperate data into training set and testing(validation) set

In [15]:
train = data[:800]
train.head()

gradient raw material human geology        rain  happen
0        27            1     1       0  650.559199       1
1        19            0     1       0  116.002018       0
2         2            0     0       1  270.352014       0
3         5            1     0       0  528.061775       0
4        23            0     1       1  380.106347       1

In [16]:
test = data[800:]
test.head()

gradient raw material human geology        rain  happen
800         0            0     1       1  120.686520       0
801        21            1     1       1  514.600300       1
802        13            0     1       1   19.219355       0
803         5            1     1       0  354.952919       0
804        20            1     0       1  606.082294       1

seperate attributes and answer

In [17]:
y = train['happen'].values
train = train.drop('happen', 1)

y

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,

# Build The Decision Tree

In [19]:
dtree=DecisionTreeClassifier(max_depth=5)
dtree.fit(train,y)

dot_data = StringIO()
export_graphviz(dtree, 
                out_file=dot_data,  
                filled=True, 
                feature_names=list(train),
                class_names=['may_happen','may_not_happen'],
                special_characters=True)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_pdf("decisiontree.pdf")

True

In [20]:
dtree.feature_importances_

array([0.59703239, 0.        , 0.        , 0.        , 0.40296761])

# calculate accuracy

In [21]:
y_test = test['happen'].values
X_test = test.drop('happen', 1)

y_predict = dtree.predict(X_test)

y_predict

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,

In [22]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_predict)

0.9985714285714286